### ISSUE TITLE
[event timeline] pop up order

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#119]
The event pop-up appears to be under the event timeline zoom in/out/centering tools.

![screen shot 2016-06-22 at 9 21 59 am](https://cloud.githubusercontent.com/assets/983575/16268140/2631dcb4-385b-11e6-819a-31d2cf7d737d.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
Still seeing this issue, although the site may be being worked on when the screenshot was taken.
![screen shot 2016-06-27 at 2 05 22 pm](https://cloud.githubusercontent.com/assets/983575/16390346/4de025ae-3c70-11e6-983a-3f06d4bf38fa.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
