### ISSUE TITLE
When there are no movies at the current observation date...

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#144]
...in the time-sensitive YouTube movie browser, it should report that there are no movies found.  Perhaps something like "No shared movies found."

**Comment by ddialer** [comment]
Done.

**Comment by wafels** [comment]
Notification still hangs around - see attached
![screen shot 2016-08-09 at 5 08 53 pm](https://cloud.githubusercontent.com/assets/983575/17533724/126a0d9a-5e54-11e6-97ef-eeca980075bf.png)

**Comment by ddialer** [comment]
corrected

**Comment by wafels** [comment]
confirmed
